In [1]:
%matplotlib notebook
import numpy as np
import pandas as pd
import os
import re
import matplotlib as mpl
mpl.get_backend()
import matplotlib.pyplot as plt

## Import spectroradiometer 12 march 2018 folder 
*this code reads each spectroradiometer file, converts the data into reflectance, save the reflectance values in dataframe and all the dataframes (belongs to different folders) are saved in a dictionary called all_data_dict*

In [2]:
folder_folders = os.walk("/home/alone/Documents/coding/Destructive/data_12_mar_2018")
folder_list = []
folder_names = []
for root, dirs, files in os.walk("/home/alone/Documents/coding/Destructive/data_12_mar_2018", topdown=False):
    for name in dirs:
        if not os.path.isfile(os.path.join(root, name)):
            folder_list.append(os.path.join(root, name))
            folder_names.append(name)
            print (os.path.join(root, name))
# print(folder_list)
print(folder_names)

all_data_dict = {}
for k in range(len(folder_list)):
    all_data = pd.DataFrame(columns=["Lambda"])
    file_list1 = os.listdir(folder_list[k])
    file_list=sorted(file_list1)
    for j in range(len(file_list)):
        raw_data = open(os.path.join(folder_list[k],file_list[j]), "r")
        f = raw_data.readlines()
        usable_part = f[78:459]
        usable_part = [i.split("  ") for i in usable_part]
        data = pd.DataFrame(usable_part)
        for index,rows in data.iterrows():
            re_pattern = r"(.*)\n"
            data.set_value(index, 2, re.search(re_pattern, rows[2]).group(1))
        data.columns=["Lambda","target","ref"]
        data.ref=pd.to_numeric(data.ref)
        data.target=pd.to_numeric(data.target)
        Reflectance=(data.target)/(data.ref)
        data=data.drop("ref",1)
        data=data.drop("target",1)
        if all_data["Lambda"].empty:
            all_data["Lambda"] = data["Lambda"]
        all_data["R"+str(j+1)]=Reflectance
    all_data_dict [folder_names[k]] = all_data
    
print("all_data_dict is a dictionary where key is folder name and stored values are dataFrame consists of reflectance values of that folder ")

/home/alone/Documents/coding/Destructive/data_12_mar_2018/D2_R2_R3_12_mar_2018
/home/alone/Documents/coding/Destructive/data_12_mar_2018/D3_R1_destructive_12_mar_2018
/home/alone/Documents/coding/Destructive/data_12_mar_2018/D2R1_destructive_12_mar_2018
['D2_R2_R3_12_mar_2018', 'D3_R1_destructive_12_mar_2018', 'D2R1_destructive_12_mar_2018']

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:26: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

all_data_dict is a dictionary where key is folder name and stored values are dataFrame consists of reflectance values of that folder

In [3]:
D3R1=all_data_dict['D3_R1_destructive_12_mar_2018']
D3R1.head()
D3R1.set_index('Lambda')
# D3R1.head()
D3R1_transposed = D3R1.T
D3R1_transposed
D3R1_transposed.columns=D3R1_transposed.iloc[0,:] 
D3R1_transposed.head()
D3R1_1=D3R1_transposed.iloc[1:,:]
D3R1_1.head()

Lambda,400.35,402.00,403.64,405.29,406.93,408.58,410.22,411.86,413.51,415.15,...,985.24,986.73,988.22,989.71,991.20,992.69,994.18,995.67,997.16,998.65
R1,0.0736641,0.0732575,0.075584,0.0753482,0.0767085,0.0794552,0.0831188,0.0851007,0.0899788,0.094042,...,0.592317,0.576414,0.590286,0.58802,0.574074,0.581967,0.576239,0.582569,0.579605,0.584362
R2,0.0974555,0.0979137,0.098832,0.0993035,0.10271,0.103197,0.106197,0.10818,0.112385,0.117222,...,0.605948,0.586643,0.599004,0.586186,0.585185,0.588272,0.587039,0.589777,0.584868,0.593278
R3,0.0947837,0.0967283,0.0957996,0.0978261,0.0985256,0.0987514,0.101048,0.101408,0.10374,0.104971,...,0.541512,0.539711,0.542964,0.540342,0.531481,0.545397,0.53939,0.540629,0.542105,0.542524
R4,0.0592214,0.0585318,0.0612714,0.0591704,0.0618249,0.0615425,0.063315,0.0637768,0.0642822,0.0667105,...,0.510922,0.504723,0.508383,0.509036,0.521066,0.500616,0.510759,0.507624,0.51039,0.520918
R5,0.0580347,0.058201,0.0603304,0.0609397,0.0629423,0.0631273,0.0655456,0.0674306,0.0690622,0.0724614,...,0.541262,0.529516,0.535928,0.536145,0.540273,0.53633,0.53481,0.52986,0.526623,0.54386

In [4]:
D2R1=all_data_dict['D2R1_destructive_12_mar_2018']
D2R1.head()
D2R1.set_index('Lambda')
D2R1_transposed = D2R1.T
D2R1_transposed
D2R1_transposed.columns=D2R1_transposed.iloc[0,:] 
D2R1_transposed.head()
D2R1_1=D2R1_transposed.iloc[1:,:]
D2R1_1.head()

Lambda,400.35,402.00,403.64,405.29,406.93,408.58,410.22,411.86,413.51,415.15,...,985.24,986.73,988.22,989.71,991.20,992.69,994.18,995.67,997.16,998.65
R1,0.111981,0.113173,0.114257,0.11844,0.122068,0.125132,0.130546,0.134265,0.139831,0.146528,...,0.667776,0.669344,0.677267,0.66313,0.670315,0.664169,0.662275,0.673267,0.655444,0.678358
R2,0.0620375,0.061622,0.0641443,0.063948,0.0654457,0.0664137,0.0689195,0.0711454,0.0732496,0.0765006,...,0.538615,0.544177,0.542625,0.540451,0.542408,0.538828,0.5319,0.536068,0.532235,0.54403
R3,0.0929141,0.093162,0.0937108,0.0949172,0.0959348,0.0949821,0.0964462,0.0973048,0.0975681,0.0989604,...,0.603196,0.609772,0.610284,0.595491,0.610123,0.600136,0.596394,0.603253,0.593123,0.606716
R4,0.101667,0.101553,0.102425,0.10332,0.105046,0.106749,0.109716,0.112055,0.114716,0.118261,...,0.622251,0.609276,0.606599,0.614138,0.614935,0.615283,0.606242,0.611035,0.610264,0.622669
R5,0.0864103,0.0844684,0.086789,0.0867205,0.0885605,0.0908745,0.0919837,0.0953318,0.0971631,0.102174,...,0.553687,0.547014,0.539975,0.540208,0.547403,0.550066,0.547145,0.55109,0.549237,0.550933

In [5]:
DAS_D3R1_12_Mar_2018=[107]*36
Nitrogen_D3R1_12_Mar_2018=[2.328,2.328,2.328,
2.5705,2.5705,2.5705,
2.9055,2.9055,2.9055,
2.902,2.902,2.902,
2.191,2.191,2.191,
3.336,3.336,3.336,
2.061,2.061,2.061,
1.9435,1.9435,1.9435,
2.1785,2.1785,2.1785,
2.855,2.855,2.855,
1.6125,1.6125,1.6125,
1.241,1.241,1.241]
Carbon_D3R1_12_Mar_2018=[40.6775,40.6775,40.6775,
40.1675,40.1675,40.1675,
40.108,40.108,40.108,
41.508,41.508,41.508,
39.505,39.505,39.505,
42.261,42.261,42.261,
39.933,39.933,39.933,
38.834,38.834,38.834,
38.5345,38.5345,38.5345,
40.9045,40.9045,40.9045,
39.651,39.651,39.651,
38.2585,38.2585,38.2585]
CNRatio_D3R1_12_Mar_2018=[17.473152921,17.473152921,17.473152921,
15.6263372885,15.6263372885,15.6263372885,
13.8041645156,13.8041645156,13.8041645156,
14.3032391454,14.3032391454,14.3032391454,
18.030579644,18.030579644,18.030579644,
12.6681654676,12.6681654676,12.6681654676,
19.3755458515,19.3755458515,19.3755458515,
19.9814767173,19.9814767173,19.9814767173,
17.6885471655,17.6885471655,17.6885471655,
14.3273204904,14.3273204904,14.3273204904,
24.5897674419,24.5897674419,24.5897674419,
30.8287671233,30.8287671233,30.8287671233]
Hydrogen_D3R1_12_Mar_2018 = [5.485,5.485,5.485,
5.5625,5.5625,5.5625,
5.2665,5.2665,5.2665,
5.902,5.902,5.902,
5.765,5.765,5.765,
5.7925,5.7925,5.7925,
5.267,5.267,5.267,
5.4585,5.4585,5.4585,
5.3525,5.3525,5.3525,
5.766,5.766,5.766,
5.5855,5.5855,5.5855,
5.201,5.201,5.201]
Water_D3R1_12_Mar_2018=[62.0,62.0,62.0,
       65.1,65.1,65.1,
       57.8,57.8,57.8,
       67.2,67.2,67.2,
       80.3,80.3,80.3,
       71.4,71.4,71.4,
       64.1,64.1,64.1,
       66.0,66.0,66.0,
       65.0,65.0,65.0,
       25.5,25.5,25.5,
       63.3,63.3,63.3,
       66.2,66.2,66.21]

DAS_D2R1_12_Mar_2018=[122]*36
Nitrogen_D2R1_12_Mar_2018=[1.902,1.902,1.902,
1.7165,1.7165,1.7165,
1.9445,1.9445,1.9445,
1.474,1.474,1.474,
1.873,1.873,1.873,
1.3615,1.3615,1.3615,
2.415,2.415,2.415,
2.039,2.039,2.039,
1.6585,1.6585,1.6585,
1.9775,1.9775,1.9775,
2.033,2.033,2.033,
1.5865,1.5865,1.5865]
Carbon_D2R1_12_Mar_2018=[38.6365,38.6365,38.6365,
39.893,39.893,39.893,
39.863,39.863,39.863,
36.62,36.62,36.62,
38.365,38.365,38.365,
38.344,38.344,38.344,
38.465,38.465,38.465,
35.867,35.867,35.867,
38.0735,38.0735,38.0735,
39.4665,39.4665,39.4665,
39.627,39.627,39.627,
39.2255,39.2255,39.2255]
Hydrogen_D2R1_12_Mar_2018=[5.454,5.454,5.454,
5.627,5.627,5.627,
5.2395,5.2395,5.2395,
5.173,5.173,5.173,
5.6485,5.6485,5.6485,
5.5045,5.5045,5.5045,
5.5275,5.5275,5.5275,
5.32,5.32,5.32,
5.6645,5.6645,5.6645,
4.936,4.936,4.936,
5.3555,5.3555,5.3555,
4.858,4.858,4.858]
CNRatio_D2R1_12_Mar_2018=[20.313617245,20.313617245,20.313617245,
23.2408971745,23.2408971745,23.2408971745,
20.5003857033,20.5003857033,20.5003857033,
24.8439620081,24.8439620081,24.8439620081,
20.483182,20.483182,20.483182,
28.1630554535,28.1630554535,28.1630554535,
15.9275362319,15.9275362319,15.9275362319,
17.5904855321,17.5904855321,17.5904855321,
22.9565872777,22.9565872777,22.9565872777,
19.9577749684,19.9577749684,19.9577749684,
19.4918839154,19.4918839154,19.4918839154,
24.7245508982,24.7245508982,24.7245508982]
Water_D2R1_12_Mar_2018=[66.0,66.0,66.0,
63.2,63.2,63.2,
63.7,63.7,63.7,
63.8,63.8,63.8,
63.9,63.9,63.9,
66.6,66.6,66.6,
66.5,66.5,66.5,
61.7,61.7,61.7,
65.0,65.0,65.0,
59.4,59.4,59.4,
66.8,66.8,66.8,
71.9,71.9,71.9]

In [6]:
D3R1_1["DAS"]=DAS_D3R1_12_Mar_2018
D3R1_1["Nitrogen"]=Nitrogen_D3R1_12_Mar_2018
D3R1_1["Carbon"]=Carbon_D3R1_12_Mar_2018
D3R1_1["CNRatio"]=CNRatio_D3R1_12_Mar_2018
D3R1_1["Hydrogen"]=Hydrogen_D3R1_12_Mar_2018
D3R1_1["Water"]=Water_D3R1_12_Mar_2018
D3R1_1.head()
D3R1_1.to_csv("D3R1_12_Mar_2018.csv")

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [19]:
D2R1_1["DAS"]=DAS_D2R1_12_Mar_2018
D2R1_1["Nitrogen"]=Nitrogen_D2R1_12_Mar_2018
D2R1_1["Carbon"]=Carbon_D2R1_12_Mar_2018
D2R1_1["CNRatio"]=CNRatio_D2R1_12_Mar_2018
D2R1_1["Hydrogen"]=Hydrogen_D2R1_12_Mar_2018
D2R1_1["Water"]=Water_D2R1_12_Mar_2018

D2R1_1.head()
# D2R1_1.to_csv("D2R1_12_Mar_2018.csv")

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Lambda,400.35,402.00,403.64,405.29,406.93,408.58,410.22,411.86,413.51,415.15,...,994.18,995.67,997.16,998.65,DAS,Nitrogen,Carbon,CNRatio,Hydrogen,Water
R1,0.111981,0.113173,0.114257,0.11844,0.122068,0.125132,0.130546,0.134265,0.139831,0.146528,...,0.662275,0.673267,0.655444,0.678358,122,1.9020,38.6365,20.313617,5.454,66.0
R2,0.0620375,0.061622,0.0641443,0.063948,0.0654457,0.0664137,0.0689195,0.0711454,0.0732496,0.0765006,...,0.5319,0.536068,0.532235,0.54403,122,1.9020,38.6365,20.313617,5.454,66.0
R3,0.0929141,0.093162,0.0937108,0.0949172,0.0959348,0.0949821,0.0964462,0.0973048,0.0975681,0.0989604,...,0.596394,0.603253,0.593123,0.606716,122,1.9020,38.6365,20.313617,5.454,66.0
R4,0.101667,0.101553,0.102425,0.10332,0.105046,0.106749,0.109716,0.112055,0.114716,0.118261,...,0.606242,0.611035,0.610264,0.622669,122,1.7165,39.8930,23.240897,5.627,63.2
R5,0.0864103,0.0844684,0.086789,0.0867205,0.0885605,0.0908745,0.0919837,0.0953318,0.0971631,0.102174,...,0.547145,0.55109,0.549237,0.550933,122,1.7165,39.8930,23.240897,5.627,63.2

In [19]:
folder_folders = os.walk("/home/alone/Documents/coding/Destructive/data_19_22_feb_2018")
folder_list = []
folder_names = []
for root, dirs, files in os.walk("/home/alone/Documents/coding/Destructive/data_19_22_feb_2018", topdown=False):
    for name in dirs:
        if not os.path.isfile(os.path.join(root, name)):
            folder_list.append(os.path.join(root, name))
            folder_names.append(name)
            print (os.path.join(root, name))
# print(folder_list)
print(folder_names)

all_data_dict = {}
for k in range(len(folder_list)):
    all_data = pd.DataFrame(columns=["Lambda"])
    file_list2 = os.listdir(folder_list[k])
    file_list=sorted(file_list2)
    for j in range(len(file_list)):
        raw_data = open(os.path.join(folder_list[k],file_list[j]), "r")
        f = raw_data.readlines()
        usable_part = f[78:459]
        usable_part = [i.split("  ") for i in usable_part]
        data = pd.DataFrame(usable_part)
        for index,rows in data.iterrows():
            re_pattern = r"(.*)\n"
            data.set_value(index, 2, re.search(re_pattern, rows[2]).group(1))
        data.columns=["Lambda","target","ref"]
        data.ref=pd.to_numeric(data.ref)
        data.target=pd.to_numeric(data.target)
        Reflectance=(data.target)/(data.ref)
        data=data.drop("ref",1)
        data=data.drop("target",1)
        if all_data["Lambda"].empty:
            all_data["Lambda"] = data["Lambda"]
        all_data["R"+str(j+1)]=Reflectance
    all_data_dict [folder_names[k]] = all_data
    
print("all_data_dict is a dictionary where key is folder name and stored values are dataFrame consists of reflectance values of that folder ")

/home/alone/Documents/coding/Destructive/data_19_22_feb_2018/D2R1_destructive_19_22_feb_2018
/home/alone/Documents/coding/Destructive/data_19_22_feb_2018/D1R1_destructive_19_22_feb_2018
/home/alone/Documents/coding/Destructive/data_19_22_feb_2018/D1_R2_R3_19_22_feb_2018
['D2R1_destructive_19_22_feb_2018', 'D1R1_destructive_19_22_feb_2018', 'D1_R2_R3_19_22_feb_2018']

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:26: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

all_data_dict is a dictionary where key is folder name and stored values are dataFrame consists of reflectance values of that folder

In [8]:
D1R1=all_data_dict['D1R1_destructive_19_22_feb_2018']
D1R1.head()
D1R1_1=D1R1.T
D1R1_1.head()
D1R1_1.columns=D1R1_1.iloc[0,:]
D1R1_1.head()
D1R1_good=D1R1_1.iloc[1:,:]
D1R1_good.head()

Lambda,400.35,402.00,403.64,405.29,406.93,408.58,410.22,411.86,413.51,415.15,...,985.24,986.73,988.22,989.71,991.20,992.69,994.18,995.67,997.16,998.65
R1,0.111727,0.11104,0.11259,0.111976,0.1127,0.113385,0.113313,0.11476,0.114894,0.117135,...,0.580914,0.558844,0.575036,0.56383,0.569203,0.575444,0.558114,0.580757,0.558623,0.578226
R2,0.114737,0.114983,0.115602,0.115359,0.116062,0.117156,0.116826,0.11712,0.118154,0.119322,...,0.592525,0.568245,0.584416,0.573404,0.576812,0.58247,0.566155,0.590031,0.565053,0.58871
R3,0.0749863,0.0751081,0.0755422,0.0749888,0.076254,0.076076,0.0768105,0.076963,0.0778688,0.0781831,...,0.5,0.478412,0.498557,0.482624,0.492754,0.492973,0.482091,0.502318,0.476551,0.504839
R4,0.0727786,0.072999,0.0737888,0.0739963,0.0738786,0.0754257,0.0773066,0.0789014,0.0817113,0.0830782,...,0.519601,0.518301,0.513736,0.52493,0.512238,0.521879,0.516594,0.511939,0.522693,0.510258
R5,0.127786,0.127896,0.128633,0.129318,0.129562,0.131645,0.133511,0.135433,0.138659,0.142194,...,0.629642,0.629144,0.621566,0.632374,0.626224,0.633429,0.628066,0.615412,0.631997,0.618161

In [20]:
D2R1=all_data_dict['D2R1_destructive_19_22_feb_2018']
D2R1.head()
D2R1_1=D2R1.T
D2R1_1.head()
D2R1_1.columns=D2R1_1.iloc[0,:]
D2R1_1.head()
D2R1_good=D2R1_1.iloc[1:,:]
D2R1_good.head()

Lambda,400.35,402.00,403.64,405.29,406.93,408.58,410.22,411.86,413.51,415.15,...,985.24,986.73,988.22,989.71,991.20,992.69,994.18,995.67,997.16,998.65
R1,0.0508136,0.05105,0.051082,0.0523094,0.0516839,0.0518281,0.0522854,0.0526625,0.0534468,0.0532655,...,0.49829,0.50307,0.499657,0.497253,0.498281,0.497872,0.495726,0.496356,0.499255,0.495076
R2,0.0690212,0.0695752,0.0686789,0.070247,0.0694867,0.0695348,0.0689366,0.0697654,0.070009,0.0708869,...,0.496922,0.497954,0.49417,0.494162,0.48315,0.496099,0.490028,0.495627,0.493294,0.485985
R3,0.0607567,0.0597393,0.0604783,0.0600967,0.0609657,0.0611122,0.0613806,0.0620036,0.0624888,0.0631691,...,0.511286,0.505116,0.508573,0.505151,0.496905,0.506738,0.499644,0.501093,0.502608,0.501136
R4,0.0548664,0.0537456,0.0557895,0.0554898,0.0574369,0.0583098,0.0606191,0.063249,0.0657613,0.0704759,...,0.585826,0.583549,0.595872,0.578125,0.591946,0.589744,0.597241,0.595339,0.577298,0.599554
R5,0.0683445,0.0658245,0.0672632,0.0664495,0.0667914,0.0673959,0.0674119,0.0682423,0.0669959,0.0696526,...,0.570871,0.553109,0.583222,0.554036,0.571141,0.561403,0.571724,0.574859,0.552228,0.575037

In [21]:
DAS_D1R1_19_Feb_2018=[115]*36
Nitrogen_D1R1_19_Feb_2018=[0.78,0.78,0.78,
1.551,1.551,1.551,
3.001,3.001,3.001,
1.64,1.64,1.64,
2.997,2.997,2.997,
1.032,1.032,1.032,
1.326,1.326,1.326,
1.936,1.936,1.936,
1.345,1.345,1.345,
1.814,1.814,1.814,
1.305,1.305,1.305,
1.015,1.015,1.015]
Carbon_D1R1_19_Feb_2018=[16.779,16.779,16.779,
21.854,21.854,21.854,
35.717,35.717,35.717,
22.477,22.477,22.477,
36.868,36.868,36.868,
16.953,16.953,16.953,
18.71,18.71,18.71,
23.488,23.488,23.488,
23.126,23.126,23.126,
21.163,21.163,21.163,
18.345,18.345,18.345,
15.221,15.221,15.221]
CNRatio_D1R1_19_Feb_2018=[21.5115384615,21.5115384615,21.5115384615,
14.0902643456,14.0902643456,14.0902643456,
11.9016994335,11.9016994335,11.9016994335,
13.7054878049,13.7054878049,13.7054878049,
12.3016349683,12.3016349683,12.3016349683,
16.4273255814,16.4273255814,16.4273255814,
14.1101055807,14.1101055807,14.1101055807,
12.132231405,12.132231405,12.132231405,
17.1940520446,17.1940520446,17.1940520446,
11.6664829107,11.6664829107,11.6664829107,
14.0574712644,14.0574712644,14.0574712644,
14.9960591133,14.9960591133,14.9960591133]
Hydrogen_D1R1_19_Feb_2018 = [8.059,8.059,8.059,
3.188,3.188,3.188,
5.489,5.489,5.489,
2.97,2.97,2.97,
5.445,5.445,5.445,
7.78,7.78,7.78,
2.427,2.427,2.427,
5.696,5.696,5.696,
4.957,4.957,4.957,
5.491,5.491,5.491,
3.366,3.366,3.366,
4.97,4.97,4.97]
Water_D1R1_19_Feb_2018=[58.54962,58.54962,58.54962,
66.87448,66.87448,66.87448,
71.0698,71.0698,71.0698,
65.72431,65.72431,65.72431,
60,60,60,
55.57746,55.57746,55.57746,
48.63775,48.63775,48.63775,
60.33834,60.33834,60.33834,
62,62,62,
61.12527,61.12527,61.12527,
62.42073,62.42073,62.42073,
58.74944,58.74944,58.74944]

#.......
DAS_D2R1_22_Feb_2018=[103]*36

Nitrogen_D2R1_22_Feb_2018=[1.19,1.19,1.19,
0.891,0.891,0.891,
0.691,0.691,0.691,
0.788,0.788,0.788,
0.82,0.82,0.82,
0.757,0.757,0.757,
0.733,0.733,0.733,
0.901,0.901,0.901,
0.772,0.772,0.772,
0.992,0.992,0.992,
0.799,0.799,0.799,
0.889,0.889,0.889]
Carbon_D2R1_22_Feb_2018=[20.723,20.723,20.723,
17.949,17.949,17.949,
16.34,16.34,16.34,
17.386,17.386,17.386,
16.297,16.297,16.297,
16.103,16.103,16.103,
15.799,15.799,15.799,
15.015,15.015,15.015,
16.941,16.941,16.941,
16.567,16.567,16.567,
15.222,15.222,15.222,
14.693,14.693,14.693]
CNRatio_D2R1_22_Feb_2018=[17.4142857143,17.4142857143,17.4142857143,
20.1447811448,20.1447811448,20.1447811448,
23.6468885673,23.6468885673,23.6468885673,
22.0634517766,22.0634517766,22.0634517766,
19.8743902439,19.8743902439,19.8743902439,
21.2721268164,21.2721268164,21.2721268164,
21.553888131,21.553888131,21.553888131,
16.6648168701,16.6648168701,16.6648168701,
21.9443005181,21.9443005181,21.9443005181,
16.7006048387,16.7006048387,16.7006048387,
19.0513141427,19.0513141427,19.0513141427,
16.5275590551,16.5275590551,16.5275590551]
Hydrogen_D2R1_22_Feb_2018= [3.917,3.917,3.917,
6.053,6.053,6.053,
7.077,7.077,7.077,
7.285,7.285,7.285,
7.189,7.189,7.189,
7.979,7.979,7.979,
7.928,7.928,7.928,
6.42,6.42,6.42,
5.435,5.435,5.435,
6.446,6.446,6.446,
7.656,7.656,7.656,
6.898,6.898,6.898]

Water_D2R1_22_Feb_2018=[0]*36

In [26]:
D1R1_good['DAS']=DAS_D1R1_19_Feb_2018
D1R1_good['Nitrogen']=Nitrogen_D1R1_19_Feb_2018
# D1R1_good.head()
D1R1_good['Carbon']=Carbon_D1R1_19_Feb_2018
D1R1_good['CNRatio'] =CNRatio_D1R1_19_Feb_2018
D1R1_good['Hydrogen'] = Hydrogen_D1R1_19_Feb_2018
D1R1_good['Water'] = Water_D1R1_19_Feb_2018
D1R1_good.head()
# D1R1_good.to_csv('D1R1_19_Feb_2018.csv')

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

Lambda,400.35,402.00,403.64,405.29,406.93,408.58,410.22,411.86,413.51,415.15,...,994.18,995.67,997.16,998.65,DAS,Nitrogen,Carbon,CNRatio,Hydrogen,Water
R1,0.111727,0.11104,0.11259,0.111976,0.1127,0.113385,0.113313,0.11476,0.114894,0.117135,...,0.558114,0.580757,0.558623,0.578226,115,0.780,16.779,21.511538,8.059,58.54962
R2,0.114737,0.114983,0.115602,0.115359,0.116062,0.117156,0.116826,0.11712,0.118154,0.119322,...,0.566155,0.590031,0.565053,0.58871,115,0.780,16.779,21.511538,8.059,58.54962
R3,0.0749863,0.0751081,0.0755422,0.0749888,0.076254,0.076076,0.0768105,0.076963,0.0778688,0.0781831,...,0.482091,0.502318,0.476551,0.504839,115,0.780,16.779,21.511538,8.059,58.54962
R4,0.0727786,0.072999,0.0737888,0.0739963,0.0738786,0.0754257,0.0773066,0.0789014,0.0817113,0.0830782,...,0.516594,0.511939,0.522693,0.510258,115,1.551,21.854,14.090264,3.188,66.87448
R5,0.127786,0.127896,0.128633,0.129318,0.129562,0.131645,0.133511,0.135433,0.138659,0.142194,...,0.628066,0.615412,0.631997,0.618161,115,1.551,21.854,14.090264,3.188,66.87448

In [22]:
D2R1_good['DAS']= DAS_D2R1_22_Feb_2018
D2R1_good['Nitrogen']= Nitrogen_D2R1_22_Feb_2018
D2R1_good['Carbon']= Carbon_D2R1_22_Feb_2018
D2R1_good['CNRatio']= CNRatio_D2R1_22_Feb_2018
D2R1_good['Hydrogen']=Hydrogen_D2R1_22_Feb_2018
D2R1_good['Water']=Water_D2R1_22_Feb_2018
D2R1_good.to_csv('D2R1_22_Feb_2018.csv')
D2R1_good.head()

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/home/alone/.local/lib/python3.5/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Lambda,400.35,402.00,403.64,405.29,406.93,408.58,410.22,411.86,413.51,415.15,...,994.18,995.67,997.16,998.65,DAS,Nitrogen,Carbon,CNRatio,Hydrogen,Water
R1,0.0508136,0.05105,0.051082,0.0523094,0.0516839,0.0518281,0.0522854,0.0526625,0.0534468,0.0532655,...,0.495726,0.496356,0.499255,0.495076,103,1.190,20.723,17.414286,3.917,0
R2,0.0690212,0.0695752,0.0686789,0.070247,0.0694867,0.0695348,0.0689366,0.0697654,0.070009,0.0708869,...,0.490028,0.495627,0.493294,0.485985,103,1.190,20.723,17.414286,3.917,0
R3,0.0607567,0.0597393,0.0604783,0.0600967,0.0609657,0.0611122,0.0613806,0.0620036,0.0624888,0.0631691,...,0.499644,0.501093,0.502608,0.501136,103,1.190,20.723,17.414286,3.917,0
R4,0.0548664,0.0537456,0.0557895,0.0554898,0.0574369,0.0583098,0.0606191,0.063249,0.0657613,0.0704759,...,0.597241,0.595339,0.577298,0.599554,103,0.891,17.949,20.144781,6.053,0
R5,0.0683445,0.0658245,0.0672632,0.0664495,0.0667914,0.0673959,0.0674119,0.0682423,0.0669959,0.0696526,...,0.571724,0.574859,0.552228,0.575037,103,0.891,17.949,20.144781,6.053,0

In [126]:
D2R1_good.head()
D2R1_good.shape

(36, 385)